#Example serverless travel app 
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: destination
  labels: 
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: moficodes/destination:v0.0.2
          env:
            - name: HOST_IP
              value: destination
            - name: SCHEME
              value: http
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: bee
spec:
  template:
    spec:
      containers:
        - image: moficodes/bee-ui:v0.0.8
          env:
            - name: DESTINATION_URL
              value: http://destination.demo.svc.cluster.local