apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bee
spec:
  template:
    metadata:
      annotations: autoscaling.knative.dev/target: "50" 
      autoscaling.knative.dev/metric: "rps"
    spec:
      containers:
        - image: moficodes/bee-ui:v0.0.8
          env:
            - name: DESTINATION_URL
              value: http://destination.travel.svc
              
