apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bee
spec:
  template:
    spec:
      containers:
        - image: moficodes/bee-ui:v0.0.8
          env:
            - name: DESTINATION_URL
              value: http://destination.aziz-bhy.svc.cluster.local
              
