apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: destination
  labels: 
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: moficodes/destination:v0.0.2
          env:
            - name: HOST_IP
              value: destination
            - name: SCHEME
              value: http